spring:
  datasource:
    url: jdbc:h2:mem:webauthn;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration/h2

app:
  fido:
    origin: https://webauthn-boot.0g0.jp
    rp:
      id: webauthn-boot.0g0.jp
      name: FidoSampleApp

logging.file: webauthn.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: info
    org.thymeleaf: info
    org.thymeleaf.TemplateEngine.CONFIG: info
    org.thymeleaf.TemplateEngine.TIMER: info
    org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE: info
    com.example.demo: info
