spring:
  datasource:
    url: jdbc:h2:mem:webauthn;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration/h2
